services:
  zzyl-admin:
    image: ${ZZYL_ADMIN_IMAGE}
    container_name: zzyl-admin
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: ${TZ}
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "${APP_PORT}:9000"
    volumes:
      - ${APP_LOG_DIR}:/home/ruoyi/logs
      - ${APP_PROFILE_DIR}:${APP_PROFILE_DIR}

  zzyl-vue3:
    image: ${ZZYL_VUE3_IMAGE}
    container_name: zzyl-vue3
    restart: unless-stopped
    depends_on:
      - zzyl-admin
    ports:
      - "${UI_PORT}:80"
